# sources:
#   - name: StackExchange
#     handler:
#       openapi:
#         source: https://raw.githubusercontent.com/grokify/api-specs/master/stackexchange/stackexchange-api-v2.2_openapi-v3.0.yaml

# documents:
#   - list-questions.query.graphql

sources: 
  - name: Countries
    handler:
      graphql:
        endpoint: https://countries.trevorblades.com/
  - name: Star wars
    handler:
      graphql:
        endpoint: https://swapi-graphql.netlify.app/.netlify/functions/index